# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 962d89ff330073365a60fac53a36a66939bd2d81c17154ffb81a98c8dc481c03e72dd4870dee927dac6435d6e4e363b7fd738e3166abaac0a210f6ac674437a9

test:
  secret_key_base: 323a5e8374fe392546611b3ae4aa684365eca99125be65af58f162ada48ef37da9590d6bbcb34e7dc1795009cf1cd44f13cf597b206ed89daf510c335c2e15a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
